default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: berjubel_development

test:
  <<: *default
  database: berjubel_test

production:
  <<: *default
  database: berjubel_production
