development:
  adapter: mysql
  database: berjubel_development
  username: root
  pool: 5
  timeout: 5000

test:
  adapter: mysql
  database: berjubel_test
  username: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  database: berjubel_production
  username: root
  pool: 5
  timeout: 5000
